"""Vendor exercise_detail (transpiled VM + exercise enums + enum-lift + adapter + generated screen)
into WFL_PseudoCoup/src. Reuses the kotlin_rt + reactive_shim already vendored by vendor_gym_list.py.
Run from PseudoCoup/tools/pseudokotlin."""
import os
import sys

HERE = "/home/lucas/Programming/PseudoCoup/tools/pseudokotlin"
sys.path.insert(0, HERE)
import oracle as O                            # noqa: E402
import pseudoui_run as R                      # noqa: E402
from transpiler import KtToPy                 # noqa: E402

APP = "/home/lucas/Programming/WFL_PseudoCoup/src"
GEN = os.path.join(APP, "generated")
hdr = ("from generated.kotlin_rt import *          # noqa: F401,F403\n"
       "from generated.reactive_shim import *      # noqa: F401,F403\n\n\n")

# 1. the exercise enums (transpiled, 1:1 -- int<->enum + displayName())
enums = ["MovementPattern.kt", "EquipmentType.kt", "MuscleGroup.kt", "WeightUnit.kt"]
parts = [KtToPy().transpile(open(O.find_one(O.MAIN, f), "rb").read()) for f in enums]
open(os.path.join(GEN, "exercise_enums_kt.py"), "w").write(
    '"""Transpiled (KtToPy) exercise enums: MovementPattern/EquipmentType/MuscleGroup/WeightUnit."""\n'
    + hdr + "\n\n".join(parts) + "\n")

# 2. the transpiled ExerciseDetailViewModel (+ ExcludePrompt)
vm_src = KtToPy().transpile(open(O.find_one(O.MAIN, "ExerciseDetailViewModel.kt"), "rb").read())
open(os.path.join(GEN, "exercise_detail_kt.py"), "w").write(
    '"""Transpiled (KtToPy) ExerciseDetailViewModel + ExcludePrompt (1:1 with Kotlin)."""\n'
    + hdr + vm_src + "\n")

# 3. the enum-lift proxy + adapter + make_vm (the framework boundary, ported once)
open(os.path.join(GEN, "exercise_detail_backend.py"), "w").write('''"""exercise_detail backend: an ExerciseEntity enum-lift PROXY (int -> transpiled enum, incl.
List<MuscleGroup>) + the adapter feeding the transpiled ExerciseDetailViewModel. The savedStateHandle
yields the router's selected exercise id; mutating actions delegate to the app ExerciseRepository."""
from generated import kotlin_rt as rt
from generated.reactive_shim import Flow
from generated.exercise_detail_kt import ExerciseDetailViewModel
from generated.exercise_enums_kt import MovementPattern, EquipmentType, MuscleGroup, WeightUnit
from data.repository.exercise_repository import ExerciseRepository

# ExerciseEntity's enum-typed fields (precomputed -- no Kotlin parsing at runtime).
_ENUM_FIELDS = {
    "primaryMuscleGroups": (MuscleGroup, True),
    "secondaryMuscleGroups": (MuscleGroup, True),
    "movementPattern": (MovementPattern, False),
    "equipmentType": (EquipmentType, False),
    "preferredUnit": (WeightUnit, False),
}


class _LiftProxy:
    """wraps the app ExerciseEntity, lifting its enum fields (int -> transpiled enum) on access."""
    def __init__(self, obj): self.__dict__["_o"] = obj

    def __getattr__(self, n):
        v = getattr(self._o, n)
        ef = _ENUM_FIELDS.get(n)
        if ef is not None and v is not None:
            cls, is_list = ef
            try:
                if is_list:
                    return rt.KtList(cls.entries[int(i)] for i in v)
                return cls.entries[int(v)]
            except Exception:                            # noqa: BLE001 -- not int-convertible; pass through
                pass
        return v


def _lift(g):
    return _LiftProxy(g) if g is not None else None


def make_vm(db, sel=None):
    repo = ExerciseRepository(db)
    eid = sel or ""

    class _Repo:
        def getById(self, _):
            return Flow(lambda: _lift(repo.get_by_id(eid)))   # thunk: re-lift on each read
        def delete(self, ex): repo.delete(ex)
        def setExcluded(self, ex, v): pass                    # app ExerciseRepository has no exclude flag
        def toggleFavorite(self, ex): pass
        def duplicate(self, ex): return ""
        def bestSubstitute(self, _): return None

    class _Prog:                                              # app has no countExerciseOccurrences ->
        def countExerciseOccurrences(self, _): return 0       # 0 = exclude directly (no swap prompt)

    class _SSH:
        def __getitem__(self, k): return eid                  # savedStateHandle[ARG_EXERCISE_ID]

    return ExerciseDetailViewModel(_SSH(), _Repo(), _Prog())
''')

# 4. the generated screen, wired to the vendored backend
cname, ir = R.build_ir(O.find_one(O.MAIN, "ExerciseDetailScreen.kt"))
src = R.emit_app_screen(ir, "exercise_detail", "ExerciseDetailScreenGen")
src = src.replace("self.vm = build_transpiled_vm('exercise_detail', self.db, _sel)",
                  "self.vm = make_vm(self.db, _sel)")
src = ('"""GENERATED by PseudoUI from Compose ExerciseDetailScreen.kt -- drop-in for the hand-built\n'
       'ExerciseDetailScreen, backed by the transpiled (1:1-with-Kotlin) ExerciseDetailViewModel."""\n'
       "from generated.exercise_detail_backend import make_vm\n\n\n" + src)
open(os.path.join(APP, "ui", "exercise_detail_screen_gen.py"), "w").write(src)

print("vendored exercise_detail:")
for f in ("generated/exercise_enums_kt.py", "generated/exercise_detail_kt.py",
          "generated/exercise_detail_backend.py", "ui/exercise_detail_screen_gen.py"):
    print(f"  {f}  ({os.path.getsize(os.path.join(APP, f))} bytes)")
