"""
runtime/coroutines.py — a SYNCHRONOUS stand-in for kotlinx.coroutines, for the non-UI foundation.

The foundation's reactive surface is: StateFlow value-holders (MutableStateFlow(x).value / .asStateFlow())
and finite Flow transforms (combine / map / first over query results). Modeled synchronously -- a Flow
carries the list of values it would emit, operators transform eagerly, and launch / withContext /
runBlocking run the block inline; Dispatchers and Job are inert context tags.

This is faithful for state holders and finite transforms. Two honest limits: it is NOT real async
streaming, and a Flow that comes from an UNIMPLEMENTED Room DAO carries no data (the DAO query bodies are
generated by Room at compile time and are absent from the Kotlin source) -- that empties combine/first,
and is the separate DATA-LAYER gap, not this module's.
"""


class CoroutineContext:
    """A Job/Dispatcher tag. `SupervisorJob() + Dispatchers.IO` combines into one inert context."""
    def __add__(self, other):
        return self


class _Dispatcher(CoroutineContext):
    pass


class Dispatchers:
    IO = _Dispatcher()
    Main = _Dispatcher()
    Default = _Dispatcher()
    Unconfined = _Dispatcher()


def SupervisorJob(parent=None):
    return CoroutineContext()


def Job(parent=None):
    return CoroutineContext()


class _Deferred:
    def __init__(self, value):
        self._v = value

    def await_(self):
        return self._v


class CoroutineScope:
    def __init__(self, context=None):
        self.coroutineContext = context if context is not None else CoroutineContext()

    def launch(self, block=None, *a, **k):      # fire-and-forget -> run inline, return an inert Job
        if callable(block):
            block()
        return CoroutineContext()

    def cancel(self, *a):
        pass


def runBlocking(*args):
    block = next((a for a in args if callable(a)), None)
    return block() if block else None


def withContext(context, block=None):
    # withContext(Dispatchers.IO) { … } -> the trailing lambda runs inline
    b = block if callable(block) else (context if callable(context) else None)
    return b() if b else None


def coroutineScope(block=None):
    return block() if callable(block) else None


def supervisorScope(block=None):
    return block() if callable(block) else None


class Flow:
    """Synchronous Flow: the list of values it would emit. Operators transform eagerly."""
    def __init__(self, values=()):
        self._values = list(values)

    def collect(self, action):
        for v in self._values:
            action(v)
        return None

    def map(self, fn):
        return Flow(fn(v) for v in self._values)

    def mapNotNull(self, fn):
        return Flow(y for y in (fn(v) for v in self._values) if y is not None)

    def filter(self, p):
        return Flow(v for v in self._values if p(v))

    def onEach(self, action):
        for v in self._values:
            action(v)
        return self

    def first(self, p=None):
        vals = self._values if p is None else [v for v in self._values if p(v)]
        if not vals:
            raise StopIteration("Flow contained no matching element")
        return vals[0]

    def firstOrNull(self, p=None):
        vals = self._values if p is None else [v for v in self._values if p(v)]
        return vals[0] if vals else None

    def drop(self, n):
        return Flow(self._values[n:])

    def take(self, n):
        return Flow(self._values[:n])

    def toList(self):
        return list(self._values)

    def distinctUntilChanged(self):
        return self

    def catch(self, *a):
        return self

    def flatMapLatest(self, fn):
        return fn(self._values[-1]) if self._values else Flow()

    def combine(self, other, transform):
        return combine(self, other, transform)

    def stateIn(self, scope=None, started=None, initialValue=None):
        return StateFlow(self._values[-1] if self._values else initialValue)

    def asStateFlow(self):
        return self


class StateFlow(Flow):
    """Read-only state holder: a current .value, modeled as a one-element Flow."""
    def __init__(self, value):
        super().__init__([value])
        self._value = value

    @property
    def value(self):
        return self._value

    def getValue(self):
        return self._value

    def asStateFlow(self):
        return self


class MutableStateFlow(StateFlow):
    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, v):
        self._value = v
        self._values = [v]

    def update(self, fn):
        self.value = fn(self._value)
        return self._value

    def getAndUpdate(self, fn):
        old = self._value
        self.value = fn(old)
        return old

    def updateAndGet(self, fn):
        self.value = fn(self._value)
        return self._value

    def tryEmit(self, v):
        self.value = v
        return True

    def emit(self, v):
        self.value = v


class MutableSharedFlow(Flow):
    def __init__(self, replay=0, extraBufferCapacity=0, onBufferOverflow=None):
        super().__init__([])

    def tryEmit(self, v):
        self._values.append(v)
        return True

    def emit(self, v):
        self._values.append(v)

    def asSharedFlow(self):
        return self


def launch(block=None, *a, **k):        # free `launch { }` -> run the block inline (synchronous model)
    return block() if callable(block) else None


def flatMapLatest(flow=None, transform=None):   # free form of Flow.flatMapLatest (usually used as a method)
    if flow is None or transform is None:
        return Flow()
    return flow.flatMapLatest(transform) if hasattr(flow, "flatMapLatest") else Flow()


class ExperimentalCoroutinesApi:        # opt-in annotation marker (dropped at its use sites)
    pass


def flowOf(*xs):
    return Flow(xs)


def emptyFlow():
    return Flow()


def flow(block=None):
    # flow { emit(x) } can't be driven synchronously without the FlowCollector receiver; honest empty.
    return Flow()


def _current(f):
    if isinstance(f, StateFlow):
        return f.value
    if isinstance(f, Flow):
        return f._values[-1] if f._values else None
    return f


def combine(*args):
    """combine(f1, f2, …, transform) -> StateFlow(transform(current(f1), current(f2), …)). A DAO-backed
    flow with no data contributes None (the data-layer gap)."""
    *flows, transform = args
    return StateFlow(transform(*[_current(f) for f in flows]))


def asStateFlow(f):
    return f.asStateFlow() if hasattr(f, "asStateFlow") else f


def first(f, p=None):           # kotlinx.coroutines.flow.first, the free-function form of f.first()
    if hasattr(f, "first"):
        return f.first(p)
    return next(x for x in f if p is None or p(x))


class SharingStarted:
    @staticmethod
    def WhileSubscribed(*a, **k):
        return None
    Eagerly = None
    Lazily = None


# ---- self-test: the parts that DON'T depend on the data layer must be correct ------------------- #
if __name__ == "__main__":
    s = MutableStateFlow(1)
    assert s.value == 1
    s.value = 2
    assert s.value == 2
    s.update(lambda x: x + 10)
    assert s.value == 12, s.value
    assert s.asStateFlow().value == 12
    a, b = MutableStateFlow(3), MutableStateFlow(4)
    c = combine(a, b, lambda x, y: x + y)
    assert c.value == 7, c.value
    assert flowOf(1, 2, 3).map(lambda x: x * 2).toList() == [2, 4, 6]
    assert flowOf(1, 2, 3).first() == 1
    assert Flow([]).firstOrNull() is None
    box = []
    CoroutineScope(SupervisorJob() + Dispatchers.IO).launch(lambda: box.append("ran"))
    assert box == ["ran"]
    assert withContext(Dispatchers.IO, lambda: 42) == 42
    print("coroutines self-test: OK")
