"""
runtime/coroutines.py — a SYNCHRONOUS stand-in for kotlinx.coroutines, for the non-UI foundation.

The foundation's reactive surface is: StateFlow value-holders (MutableStateFlow(x).value / .asStateFlow())
and finite Flow transforms (combine / map / first over query results). Modeled synchronously -- a Flow
carries the list of values it would emit, operators transform eagerly, and launch / withContext /
runBlocking run the block inline; Dispatchers and Job are inert context tags.

This is faithful for state holders and finite transforms. Two honest limits: it is NOT real async
streaming, and a Flow that comes from an UNIMPLEMENTED Room DAO carries no data (the DAO query bodies are
generated by Room at compile time and are absent from the Kotlin source) -- that empties combine/first,
and is the separate DATA-LAYER gap, not this module's.
"""


class CoroutineContext:
    """A Job/Dispatcher tag. `SupervisorJob() + Dispatchers.IO` combines into one inert context."""
    def __add__(self, other):
        return self


class _Dispatcher(CoroutineContext):
    pass


class Dispatchers:
    IO = _Dispatcher()
    Main = _Dispatcher()
    Default = _Dispatcher()
    Unconfined = _Dispatcher()


def SupervisorJob(parent=None):
    return CoroutineContext()


def Job(parent=None):
    return CoroutineContext()


class _Deferred:
    def __init__(self, value):
        self._v = value

    def await_(self):
        return self._v


class CoroutineScope:
    def __init__(self, context=None):
        self.coroutineContext = context if context is not None else CoroutineContext()

    def launch(self, block=None, *a, **k):      # fire-and-forget -> run inline, return an inert Job
        if callable(block):
            block()
        return CoroutineContext()

    def cancel(self, *a):
        pass


def runBlocking(*args):
    block = next((a for a in args if callable(a)), None)
    return block() if block else None


def withContext(context, block=None):
    # withContext(Dispatchers.IO) { … } -> the trailing lambda runs inline
    b = block if callable(block) else (context if callable(context) else None)
    return b() if b else None


def coroutineScope(block=None):
    return block() if callable(block) else None


def supervisorScope(block=None):
    return block() if callable(block) else None


class Flow:
    """Synchronous Flow: the list of values it would emit. Operators transform eagerly.

    Liveness (`_add_listener`/`_remove_listener`/`_push`) is the SAME shared mechanism used by
    `combine()`'s `_link_live()` below and by `runtime/room.py`'s `_LiveMixin` (duck-typed, so this
    module never imports room.py): any Flow -- plain or Room-backed -- can register listeners and
    relay re-emissions. `flatMapLatest` is the one operator that both CONSUMES upstream liveness
    (subscribes to `self`) and PRODUCES it (the returned Flow relays the current inner flow's
    emissions), so it needs the full add/remove/push surface, not just `_link_live`'s one-way
    "recompute and push" helper.
    """
    def __init__(self, values=()):
        self._values = list(values)
        self._listeners = []

    def _add_listener(self, cb):
        self._listeners.append(cb)

    def _remove_listener(self, cb):
        try:
            self._listeners.remove(cb)
        except ValueError:
            pass

    def _push(self, value):
        self._values = [value]
        for cb in list(self._listeners):
            cb(value)

    def collect(self, action):
        for v in self._values:
            action(v)
        add = getattr(self, "_add_listener", None)   # stay subscribed: re-run the collector on re-emission
        if callable(add):
            add(action)
        return None

    def collectLatest(self, action):    # synchronous model: only the LATEST value is ever delivered
        if self._values:
            action(self._values[-1])
        add = getattr(self, "_add_listener", None)
        if callable(add):
            add(action)
        return None

    def map(self, fn):
        out = Flow(fn(v) for v in self._values)
        add = getattr(self, "_add_listener", None)
        if callable(add):
            add(lambda v: out._push(fn(v)))
        return out

    def mapNotNull(self, fn):
        out = Flow(y for y in (fn(v) for v in self._values) if y is not None)

        def _relay(v):
            y = fn(v)
            if y is not None:
                out._push(y)
        add = getattr(self, "_add_listener", None)
        if callable(add):
            add(_relay)
        return out

    def filter(self, p):
        out = Flow(v for v in self._values if p(v))

        def _relay(v):
            if p(v):
                out._push(v)
        add = getattr(self, "_add_listener", None)
        if callable(add):
            add(_relay)
        return out

    def onEach(self, action):
        for v in self._values:
            action(v)
        add = getattr(self, "_add_listener", None)
        if callable(add):
            add(action)
        return self

    def first(self, p=None):
        vals = self._values if p is None else [v for v in self._values if p(v)]
        if not vals:
            raise StopIteration("Flow contained no matching element")
        return vals[0]

    def firstOrNull(self, p=None):
        vals = self._values if p is None else [v for v in self._values if p(v)]
        return vals[0] if vals else None

    def drop(self, n):
        return Flow(self._values[n:])

    def take(self, n):
        return Flow(self._values[:n])

    def toList(self):
        return list(self._values)

    def distinctUntilChanged(self):
        return self

    def debounce(self, _ms):            # synchronous model: no timing -- the latest value stands
        return self

    def catch(self, *a):
        return self

    def flatMapLatest(self, fn):
        """Kotlin semantics: re-run `fn` against the LATEST upstream value every time `self` re-emits
        (duck-typed via `self._add_listener`, the same mechanism `combine()`'s `_link_live()` uses),
        cancel the subscription to the PREVIOUS inner flow before subscribing to the new one (so a
        stale inner can never leak a value through after the switch -- real cancel, not a stale-value
        guard), and relay the current inner flow's own re-emissions (if it is itself live) onward."""
        inner = fn(self._values[-1]) if self._values else Flow()
        out = Flow(list(getattr(inner, "_values", [])))
        current = {"inner": inner}

        def _make_relay(for_inner):
            def _relay(value):
                if current["inner"] is for_inner:   # guards a callback already mid-flight when swapped
                    out._push(value)
            return _relay

        def _subscribe(new_inner):
            relay = _make_relay(new_inner)
            add = getattr(new_inner, "_add_listener", None)
            if callable(add):
                add(relay)
            return relay

        relay = _subscribe(inner)

        def _on_new(value):
            nonlocal relay
            old_inner, old_relay = current["inner"], relay
            remove = getattr(old_inner, "_remove_listener", None)   # cancel the OLD inner's subscription
            if callable(remove):
                remove(old_relay)
            new_inner = fn(value)               # a NEW upstream value -> re-derive the inner flow
            current["inner"] = new_inner
            out._push(new_inner._values[-1] if getattr(new_inner, "_values", None) else None)
            relay = _subscribe(new_inner)

        add_self = getattr(self, "_add_listener", None)
        if callable(add_self):
            add_self(_on_new)
        return out

    def combine(self, other, transform):
        return combine(self, other, transform)

    def stateIn(self, scope=None, started=None, initialValue=None):
        sf = MutableStateFlow(self._values[-1] if self._values else initialValue)
        add = getattr(self, "_add_listener", None)   # stay live: upstream re-emission updates sf.value
        if callable(add):
            add(lambda v: setattr(sf, "value", v))
        return sf.asStateFlow()

    def asStateFlow(self):
        return self


class StateFlow(Flow):
    """Read-only state holder: a current .value, modeled as a one-element Flow."""
    def __init__(self, value):
        super().__init__([value])
        self._value = value

    @property
    def value(self):
        return self._value

    def getValue(self):
        return self._value

    def asStateFlow(self):
        return self

    def collectAsState(self, *a, **k):
        # Compose: read .value in a composition. This State-view IS the flow (its .value is current); a
        # MutableStateFlow write invalidates recompose, so the screen repaints. Returns self.
        return self

    collectAsStateWithLifecycle = collectAsState


class MutableStateFlow(StateFlow):
    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, v):
        self._value = v
        self._push(v)                                # updates self._values AND notifies any listeners
        try:
            import runtime.reactive as _reactive     # a VM state write -> one recompose (bridge to the kit)
            _reactive.recompose.invalidate()
        except Exception:                            # noqa: BLE001 -- no kit/scheduler in scope -> just hold
            pass

    def update(self, fn):
        self.value = fn(self._value)
        return self._value

    def getAndUpdate(self, fn):
        old = self._value
        self.value = fn(old)
        return old

    def updateAndGet(self, fn):
        self.value = fn(self._value)
        return self._value

    def tryEmit(self, v):
        self.value = v
        return True

    def emit(self, v):
        self.value = v


class MutableSharedFlow(Flow):
    def __init__(self, replay=0, extraBufferCapacity=0, onBufferOverflow=None):
        super().__init__([])

    def tryEmit(self, v):
        self._deliver(v)
        return True

    def emit(self, v):
        self._deliver(v)

    def _deliver(self, v):
        # SharedFlow is a HOT, event-style flow: an emit must NOTIFY every currently-registered collector
        # (a LaunchedEffect { flow.collect { ... } } registers one via Flow.collect -> _add_listener). The
        # old impl only did `self._values.append(v)`, which buffers but never calls the listeners -- so a
        # one-shot event emitted AFTER a collector subscribed (the normal case: LaunchedEffect collects at
        # mount, the emit happens later on a tap) was silently dropped. That killed every SharedFlow-driven
        # navigation/side-effect on py (e.g. WorkoutExecution's finishEarly -> _navigateToSummary.emit ->
        # never reached the collector -> "Finish" did nothing). We KEEP the buffer append so the reverse
        # ordering (emit before a collector subscribes -> drained by the next collect) still works, AND now
        # notify live listeners so the common collect-then-emit path fires. General fix: one place, every
        # SharedFlow event.
        self._values.append(v)
        for cb in list(self._listeners):
            cb(v)

    def asSharedFlow(self):
        return self


def launch(block=None, *a, **k):        # free `launch { }` -> run the block inline (synchronous model)
    return block() if callable(block) else None


def flatMapLatest(flow=None, transform=None):   # free form of Flow.flatMapLatest (usually used as a method)
    if flow is None or transform is None:
        return Flow()
    return flow.flatMapLatest(transform) if hasattr(flow, "flatMapLatest") else Flow()


class ExperimentalCoroutinesApi:        # opt-in annotation marker (dropped at its use sites)
    pass


def flowOf(*xs):
    return Flow(xs)


def emptyFlow():
    return Flow()


def flow(block=None):
    # flow { emit(x) } can't be driven synchronously without the FlowCollector receiver; honest empty.
    return Flow()


def _current(f):
    if isinstance(f, StateFlow):
        return f.value
    if isinstance(f, Flow):
        return f._values[-1] if f._values else None
    return f


def _link_live(flows, recompute, sink):
    """If any input Flow is a live Room query (`_LiveFlow`, duck-typed via `_add_listener` so this module
    doesn't need to import room.py), re-run `recompute()` and push the new value into `sink` whenever any
    of them re-emits -- lets combine()/stateIn() chains built on top of a Room Flow stay live too."""
    for f in flows:
        add = getattr(f, "_add_listener", None)
        if callable(add):
            add(lambda _v: sink(recompute()))


def combine(*args):
    """combine(f1, f2, …, transform) -> StateFlow(transform(current(f1), current(f2), …)). A DAO-backed
    flow with no data contributes None (the data-layer gap). Stays live: if any input is a live Room
    query Flow, a table invalidation re-runs `transform` and updates the returned StateFlow's .value."""
    *flows, transform = args
    if len(flows) == 1 and isinstance(flows[0], (list, tuple)):
        # Kotlin's collection overload `combine(flows) { arr -> ... }`: the transform receives the
        # current values as ONE array argument, not spread varargs.
        from .kotlin_rt import KtList
        inputs = flows[0]

        def recompute():
            return transform(KtList(_current(f) for f in inputs))
        result = MutableStateFlow(recompute())
        _link_live(inputs, recompute, lambda v: setattr(result, "value", v))
        return result.asStateFlow()

    def recompute():
        return transform(*[_current(f) for f in flows])
    result = MutableStateFlow(recompute())
    _link_live(flows, recompute, lambda v: setattr(result, "value", v))
    return result.asStateFlow()


def asStateFlow(f):
    return f.asStateFlow() if hasattr(f, "asStateFlow") else f


def first(f, p=None):           # kotlinx.coroutines.flow.first, the free-function form of f.first()
    if hasattr(f, "first"):
        return f.first(p)
    return next(x for x in f if p is None or p(x))


class SharingStarted:
    @staticmethod
    def WhileSubscribed(*a, **k):
        return None
    Eagerly = None
    Lazily = None


# ---- self-test: the parts that DON'T depend on the data layer must be correct ------------------- #
if __name__ == "__main__":
    s = MutableStateFlow(1)
    assert s.value == 1
    s.value = 2
    assert s.value == 2
    s.update(lambda x: x + 10)
    assert s.value == 12, s.value
    assert s.asStateFlow().value == 12
    a, b = MutableStateFlow(3), MutableStateFlow(4)
    c = combine(a, b, lambda x, y: x + y)
    assert c.value == 7, c.value
    assert flowOf(1, 2, 3).map(lambda x: x * 2).toList() == [2, 4, 6]
    assert flowOf(1, 2, 3).first() == 1
    assert Flow([]).firstOrNull() is None
    box = []
    CoroutineScope(SupervisorJob() + Dispatchers.IO).launch(lambda: box.append("ran"))
    assert box == ["ran"]
    assert withContext(Dispatchers.IO, lambda: 42) == 42
    print("coroutines self-test: OK")
